name: Be Your Own Accountant
favicon: null
layout_spectrum: 0.10421397862955928
typography_spectrum: 0.50846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#190130'
    - '#90659d'
    - '#a5d6d2'
    - '#2577a7'
    - '#6aa3be'
  brandStrength: 0.5309151662513614
  lightness: 0.6547096357680857
  saturation: 0.5468594238627702
  rhythmicContrast: 0.7861352129839361
purpose: []
